### ISSUE TITLE
Error in all stories if this addon is included

### ISSUE THREAD

**Issue by SuneRadich** [Jakob-em/storybook-addon-angular-router#22]
I am in the process of upgrading our nx mono-repo (https://nx.dev) to latest version of Angular and Storybook (going from Storybook 7.0.12 to 7.3.1).  The migration went fine, and my storybooks start up just fine. All stories however, reports the following error

```
beforeEach is not defined
ReferenceError: beforeEach is not defined
    at ./node_modules/@angular/core/fesm2022/testing.mjs (http://localhost:4400/vendors-node_modules_angular_material_fesm2022_icon_mjs-node_modules_ngrx_effects_fesm2022_ng-0729bf.iframe.bundle.js:108374:1)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:353:21)
    at ./node_modules/@angular/router/fesm2022/testing.mjs (http://localhost:4400/vendors-node_modules_angular_material_fesm2022_icon_mjs-node_modules_ngrx_effects_fesm2022_ng-0729bf.iframe.bundle.js:122382:79)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:353:21)
    at ./node_modules/storybook-addon-angular-router/dist/withAngularRouter.js (http://localhost:4400/vendors-node_modules_angular_material_fesm2022_icon_mjs-node_modules_ngrx_effects_fesm2022_ng-0729bf.iframe.bundle.js:173822:16)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:353:21)
    at ./node_modules/storybook-addon-angular-router/dist/preset/preview.js (http://localhost:4400/vendors-node_modules_angular_material_fesm2022_icon_mjs-node_modules_ngrx_effects_fesm2022_ng-0729bf.iframe.bundle.js:173789:26)
```

I have pinpointed this addon as the culprit, because the error goes away, and all stories render again if I remove the addon from the `addons` array in main.ts.

As far as I can see the addon should be compatible with Storybook 7 (and worked fine on 7.0.12). I have not investigated more, but I suspect that it is related to changes in the Angular Router.

We went from Angular `15.2.8` to `~16.2.0`

**Version information**

```
 mono git:(feature/update-nx) ✗ npx sb info  

Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.5.1
  npmPackages:
    @storybook/addon-a11y: ~7.3.1 => 7.3.1 
    @storybook/addon-essentials: ~7.3.1 => 7.3.1 
    @storybook/addon-links: ~7.3.1 => 7.3.1 
    @storybook/addon-mdx-gfm: ~7.3.1 => 7.3.1 
    @storybook/addons: ~7.3.1 => 7.3.1 
    @storybook/angular: ~7.3.1 => 7.3.1 
    @storybook/core-server: ~7.3.1 => 7.3.1 
    @storybook/manager-api: ~7.3.1 => 7.3.1 
    @storybook/theming: ~7.3.1 => 7.3.1 
```

And we have been using version 1.9.0 of this addon since before we did the latest migration.

Any idea what might cause this issue?

**Comment by Jakob-em** [comment]
Hi @SuneRadich,
thanks for the detailed report. I had a look at the issue and it looks like the angular upgrade from 16 to 16.2 introduced the issue.

I prepared a fix for the issue that is available on npm as version `1.9.1--canary.23.fa4b7fa.0`. Feel free to try it out and report back if it fixes the issue also on your side.

I will check in the coming days if there is a better solution to fix the problem as the current fix involves polyfilling some testing methods. The root cause for the issue is that the angular testing module now expects that it is running in a context where Jasmine, Mocha, or a similar framework is available and as I am importing it inside the storybook code this is not given.

**Comment by SuneRadich** [comment]
I just tried the canary version, and I can confirm that it works.

**Comment by nclskfm** [comment]
> I just tried the canary version, and I can confirm that it works.

**+1** The canary version fixes the issue. Thanks for the fast fix @Jakob-em.

**Comment by nclskfm** [comment]
@Jakob-em, is it possible to merge the pull request and publish 1.9.1? :)
