### ISSUE TITLE
Error: Cannot find module '@storybook/global'

### ISSUE THREAD

**Issue by edugouvfr** [Jakob-em/storybook-addon-angular-router#26]
Hi, I tried to integrate your addon using the context described below:
- Storybook 7.6.3 (also tried using 7.5)
- Angular 16.2.10

But when I start Storybook I got the following error using Firefox: 

```
Error: Cannot find module '@storybook/global'
    webpackEmptyContext sync:2
    js index.js:23
    Angular 2
    Webpack 25
[runtime.js:4:101929](http://localhost:6006/sb-preview/runtime.js)
    error runtime.js:4
    renderPreviewEntryError runtime.js:89
    renderPreviewEntryError runtime.js:103
    getProjectAnnotationsOrRenderError runtime.js:87
    _runRejections runtime.js:4
    _runRejections runtime.js:4
    catch runtime.js:4
    getProjectAnnotationsOrRenderError runtime.js:87
    initialize runtime.js:81
    js storybook-config-entry.js:25
```

Same error but using Chrome which provides a more explicit stack-trace:

```
   runtime.js:4 Error: Cannot find module '@storybook/global'
    at webpackEmptyContext ( sync:2:1)
    at ../../lib/channels/dist/index.js (index.js:23:1)
    at index.js:8:1
    at ./node_modules/@storybook/addon-actions/dist/index.js (index.js:23:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/storybook-addon-angular-router/dist/actionLoggingRouter.js (actionLoggingRouter.js:7:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/storybook-addon-angular-router/dist/withAngularRouter.js (withAngularRouter.js:10:1
```

    
To reproduce:

1. `npx @angular/cli@16.2 new mylib --no-create-application`
2. `cd mylib/`
3. `npx @angular/cli@16.2 generate library my-lib`
4. `npx storybook@latest init`
5. `npm i -D storybook-addon-angular-router`
6. Add the storybook-addon-angular-router addon in `/mylib/projects/my-lib/.storybook/main.ts`
7. `ng run my-lib:storybook`
8. Access http://localhost:6006/
9. F12 to show JS console and check the error

**Comment by Jakob-em** [comment]
Thanks for reporting, will take a look at whats the problem here in the coming days

**Comment by Jakob-em** [comment]
I had a look at this and it seems to be the same issue that is described [here](https://github.com/storybookjs/storybook/issues/25130) on storybook side.

Until the underlying problem is fixed the easiest solution is to stay on storybook version `7.5.3` as this one is working fine.

**Comment by homj** [comment]
> Until the underlying problem is fixed the easiest solution is to stay on storybook version `7.5.3` as this one is working fine.

I tried this solution, as well as explicitly installing `@storybook/global`, but neither worked. Only removing `storybook-addon-angular-router` entirely "fixed" it.

**Comment by anoack93** [comment]
> I had a look at this and it seems to be the same issue that is described [here](https://github.com/storybookjs/storybook/issues/25130) on storybook side.
> 
> Until the underlying problem is fixed the easiest solution is to stay on storybook version `7.5.3` as this one is working fine.

The issue is closed and it seems like the issue was fixed for other addons

**Comment by maddesigns** [comment]
same for me, as @jwittekind and @homj mentioned – the error disappered when I uninstalled storybook-addon-angular-router

**Comment by Jakob-em** [comment]
Looking at the up to date version of the storybook addon template (https://github.com/storybookjs/addon-kit) the way the addons are built/packaged seems to differ from back when I created this addon. It could be worth to try migrating to the new setup and see if it solves this issue. Will see if I find time for this in the coming weeks.
